#!/bin/bash

CCS="gcc-10 gcc-9 gcc-8 gcc-7 clang-10 clang-9 clang-8 clang-7 clang-6.0"
PERLS="5.6.2 5.8.9 5.10.1 5.12.5 5.14.4 5.16.3 5.18.4 5.20.3 \
5.22.4 5.24.4 5.26.3 5.28.3 5.30.0 5.30.1 5.30.2 5.30.3 5.32.0"

CCS="gcc-10"

function install_perl () {
    ver=$1
    cc=$2

    perl="perl-$ver"
    folder="$PERLBREW_ROOT/perls/$perl"

    if [[ ! -e "$folder" ]] ; then
        cmd="perlbrew install -j 5 -Dcc=$cc --noman $perl"
        echo "======$cmd======"

        $cmd

        if [[ -e "$folder" ]] ; then
            perlbrew list > /dev/null # force addition of .version files
            git add $folder
            git commit -m "$cmd"
        fi
    fi
}

function f () {
    [[ -f "$PROGRESS" ]] && rm "$PROGRESS"

    for cc in $CCS ; do # LEAVE UNQUOTED
        which=$(which "$cc")
        if [[ "$which" == "" || ! -x $which ]] ; then
            echo "$cc not found"
            return
        fi
    done

    for ver in $PERLS ; do # LEAVE UNQUOTED
        perl="perl-$ver"
        for cc in $CCS ; do # LEAVE UNQUOTED
            install_perl $ver $cc
        done
    done
}

f
unset f
unset install_perl
